Fixed pointing relations not having a namespace in ANNISExporter
korpling/pepperModules-ANNISModules pull request #8
Opened 2016-09-09 17:47 UTC by amir-zeldes

* Pointing relation namespaces now correctly appear in component.annis
  * The default `default_ns` is only used if a pointing relation has no SLayer or if it is
  * Adjusted test case in testIDEscape to create the escaped namespace instead of default_ns
  * Fixes korpling/pepperModules-ANNISModules#7

2016-10-12 08:47 UTC, thomaskrause requested changes

2016-10-12 08:47 UTC, thomaskrause commented on src/main/java/org/corpus_tools/peppermodules/annis/SPointingRelation2ANNISMapper.java
> +      GlobalIdManager globalIdManager = new GlobalIdManager();
There should be only one instance of the global ID Manager, you could use
```
this.idManager.getGlobal()
```
or use
```
this.idManager.getEscapedIdentifier(...)
```
instead to the the actual instance.

2016-10-12 08:47 UTC, thomaskrause commented on src/main/java/org/corpus_tools/peppermodules/annis/SPointingRelation2ANNISMapper.java
> +          String escapedLayerName = globalIdManager.getEscapedIdentifier(layerName);
Shouldn't the escaping be handled in SRelation2ANNISMapper#mapComponent2ANNIS() ?

2016-10-13 15:15 UTC, amir-zeldes commented
Thanks - I changed this in e8b51fd - is this what you meant?

2016-10-20 13:37 UTC, thomaskrause approved these changes

2016-10-20 13:37 UTC, merged